#!/usr/bin/env bash
# Apply / list / interactively choose atomcam_tools build profiles.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../../" && pwd)"
MANIFEST="$ROOT/configs/build_profiles/manifest.sh"
ACTIVE_NAME="$ROOT/target/active_profile.name"
ACTIVE_ENV="$ROOT/target/active_build_profile.env"

. "$MANIFEST"

usage() {
  cat <<'EOF'
usage: build-profile.sh <command> [args]

commands:
  list                 利用可能な PROFILE 一覧
  show [PROFILE]       PROFILE の説明と設定
  apply PROFILE        PROFILE を適用（active_profile.* を更新）
  ensure               PROFILE 未設定なら tailscale を適用
  configure            対話式プロファイル選択（Cursor 不要）
  current              現在の PROFILE を表示
  agent-hint           Cursor エージェント検出結果

環境変数:
  PROFILE              apply / ensure で使うプロファイル名
  NONINTERACTIVE=1     configure で既定 tailscale を選ぶ
EOF
}

write_active_env() {
  local profile="$1"
  profile_apply_vars "$profile" || return 1
  mkdir -p "$(dirname "$ACTIVE_ENV")"
  cat >"$ACTIVE_ENV" <<EOF
# Generated by scripts/make/build-profile.sh — do not edit by hand
BUILD_PROFILE=$profile
PROFILE_FRAGMENT=$PROFILE_FRAGMENT
INCLUDE_TAILSCALE=$INCLUDE_TAILSCALE
INCLUDE_HIL_ASSETS=$INCLUDE_HIL_ASSETS
INCLUDE_HARNESS_MMC=$INCLUDE_HARNESS_MMC
INCLUDE_AGENT_KEYS=$INCLUDE_AGENT_KEYS
SD_PACKAGE_AFTER_BUILD=$SD_PACKAGE_AFTER_BUILD
EOF
  echo "$profile" >"$ACTIVE_NAME"
}

cmd_list() {
  local p
  for p in $BUILD_PROFILE_ALL; do
    printf "  %-10s %s\n" "$p" "$(profile_desc "$p")"
  done
}

cmd_show() {
  local profile="${1:-}"
  if [ -z "$profile" ]; then
    cmd_current
    return
  fi
  if ! profile_apply_vars "$profile"; then
    echo "unknown profile: $profile" >&2
    exit 1
  fi
  echo "PROFILE=$profile"
  echo "desc: $(profile_desc "$profile")"
  echo "PROFILE_FRAGMENT=$PROFILE_FRAGMENT"
  echo "INCLUDE_TAILSCALE=$INCLUDE_TAILSCALE"
  echo "INCLUDE_HIL_ASSETS=$INCLUDE_HIL_ASSETS"
  echo "INCLUDE_HARNESS_MMC=$INCLUDE_HARNESS_MMC"
  echo "INCLUDE_AGENT_KEYS=$INCLUDE_AGENT_KEYS"
  echo "SD_PACKAGE_AFTER_BUILD=$SD_PACKAGE_AFTER_BUILD"
}

cmd_current() {
  if [ -f "$ACTIVE_NAME" ]; then
    echo "active: $(cat "$ACTIVE_NAME")"
    [ -f "$ACTIVE_ENV" ] && cat "$ACTIVE_ENV"
  else
    echo "active: (none — default tailscale on next build)"
  fi
}

cmd_apply() {
  local profile="${1:-}"
  if [ -z "$profile" ]; then
    echo "apply requires PROFILE name" >&2
    exit 1
  fi
  write_active_env "$profile"
  echo "build-profile: applied $profile"
  cmd_show "$profile"
}

cmd_ensure() {
  local profile="${PROFILE:-}"
  if [ -z "$profile" ] && [ -f "$ACTIVE_NAME" ]; then
    profile="$(cat "$ACTIVE_NAME")"
  fi
  if [ -z "$profile" ]; then
    profile=tailscale
  fi
  write_active_env "$profile"
}

cmd_agent_hint() {
  "$ROOT/scripts/make/agent-detect.sh"
}

cmd_configure() {
  if [ "${NONINTERACTIVE:-}" = "1" ]; then
    cmd_apply tailscale
    return
  fi
  "$ROOT/scripts/make/agent-detect.sh" --banner || true
  echo ""
  echo "AtomCam ビルドプロファイルを選んでください（Cursor エージェントなしでも使えます）"
  echo ""
  cmd_list
  echo ""
  printf "番号または名前 [既定: tailscale]: "
  local choice
  read -r choice || choice=tailscale
  case "$choice" in
    1|simple) choice=simple ;;
    2|tailscale|"") choice=tailscale ;;
    3|hil) choice=hil ;;
    4|cyclo) choice=cyclo ;;
    5|harness) choice=harness ;;
    6|agent) choice=agent ;;
    7|full) choice=full ;;
  esac
  cmd_apply "$choice"
  echo ""
  echo "次: make build   または   make build PROFILE=$choice"
}

main() {
  local cmd="${1:-help}"
  shift || true
  case "$cmd" in
    list) cmd_list ;;
    show) cmd_show "${1:-}" ;;
    apply) cmd_apply "${1:-}" ;;
    ensure) cmd_ensure ;;
    configure) cmd_configure ;;
    current) cmd_current ;;
    agent-hint) cmd_agent_hint ;;
    help|-h|--help) usage ;;
    *) echo "unknown command: $cmd" >&2; usage >&2; exit 1 ;;
  esac
}

main "$@"
