#!/bin/sh

HACK_INI=/tmp/hack.ini

# debug 残骸の検知: /media/mmc/crontab は -DebugBoot 等が置く追加エントリ。マージ自体は
# 仕様として維持するが、残置事故(wifi_audit 暴走で SD 逼迫等)に気付けるよう痕跡を残す。
# 撤去は scripts/hil/cleanup-debug-boot.sh(リポジトリ側)を使う。
if [ -f /media/mmc/crontab ]; then
  echo "$(date) WARN: /media/mmc/crontab merged into crontab (debug leftover?)" >> /media/mmc/atomhack.log
fi

/usr/bin/awk -F "=" '
BEGIN {
  printf("#  DO NOT EDIT THIS FILE\n");
  printf("*/15 * * * * /usr/sbin/logrotate /etc/logrotate.conf\n");
  printf("5 * * * * /scripts/remove_old.sh\n");
  printf("10 * * * * /scripts/memory_check.sh\n");
  printf("* * * * * /scripts/health_check.sh\n");
  printf("* * * * * /scripts/lighttpd.sh watchdog >> /media/mmc/atomhack.log\n");
  printf("* * * * * /scripts/rtspserver.sh watchdog >> /media/mmc/atomhack.log\n");
  printf("* * * * * /atom_patch/system_bin/mount_cifs.sh watchdog >> /media/mmc/atomhack.log\n");
  while((getline line < "/media/mmc/crontab") == 1) {
    print line;
  }
}

/^REBOOT_SCHEDULE *=/ {
  if($2 == "") next;
  gsub(/:/,",", $2);
  printf("%s /scripts/reboot.sh\n", $2);
}

/^TIMELAPSE_SCHEDULE *=/ {
  split($2, schedule, ";");
  for(i in schedule) {
    if(schedule[i] == "") continue;
    gsub(/:/,",", schedule[i]);
    printf("%s %d\n", schedule[i], i);
  }
}
' $HACK_INI | crontab -
